[package]
name = "joystick_rs"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "A Video gateway written in Rust"
authors = ["Ross Newman <ross.newman@astutesys.com>"]
homepage = "https://www.astutesys.com"

[dependencies]
tokio = "1.0.0"
gilrs = "0.11.0"
