
set(DATE_TIME_FORMAT "+%Y-%m-%d %H:%M:%S")
execute_process(COMMAND date "${DATE_TIME_FORMAT}" OUTPUT_VARIABLE BUILD_DATE OUTPUT_STRIP_TRAILING_WHITESPACE)
message(STATUS "Build date: ${BUILD_DATE}")
file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/version VERSION_CONTENTS)
list(GET VERSION_CONTENTS 0 MAJOR_VERSION)
list(GET VERSION_CONTENTS 1 MINOR_VERSION)
list(GET VERSION_CONTENTS 2 PATCH_VERSION)
list(GET VERSION_CONTENTS 3 SUFFIX)
set(VERSION ${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION})
execute_process(COMMAND git rev-parse --short HEAD OUTPUT_VARIABLE GIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE)
message(STATUS "Version (${PROJECT_NAME}): ${VERSION}${SUFFIX}")

set(VERSION_FILE ${CMAKE_CURRENT_BINARY_DIR}/include/mediax_version.h)
file(WRITE ${VERSION_FILE} "// This file it automatically generated, no not edit manually\n")
file(APPEND ${VERSION_FILE} "#include <cstdint>\n")
file(APPEND ${VERSION_FILE} "#include <string>\n")
file(APPEND ${VERSION_FILE} "\n")
file(APPEND ${VERSION_FILE} "namespace mediax {\n")
file(APPEND ${VERSION_FILE} "const uint32_t kMajor = ${MAJOR_VERSION};\n")
file(APPEND ${VERSION_FILE} "const uint32_t kMinor = ${MINOR_VERSION};\n")
file(APPEND ${VERSION_FILE} "const uint32_t kPatch = ${PATCH_VERSION};\n")
file(APPEND ${VERSION_FILE} "const std::string kSuffix = \"${SUFFIX}\";\n")
file(APPEND ${VERSION_FILE} "const std::string kVersion = \"${VERSION}\";\n")
file(APPEND ${VERSION_FILE} "const std::string kGitHash = \"${GIT_HASH}\";\n")
file(APPEND ${VERSION_FILE} "}  // namespace mediax\n")

set(C_VERSION_FILE ${CMAKE_SOURCE_DIR}/drivers/tw686x/version.h)
file(WRITE ${C_VERSION_FILE} "// This file it automatically generated, no not edit manually\n")
file(APPEND ${C_VERSION_FILE} "#ifndef DRIVERS_TW686X_VERSION_H_\n")
file(APPEND ${C_VERSION_FILE} "#define DRIVERS_TW686X_VERSION_H_\n")
file(APPEND ${C_VERSION_FILE} "\n")
file(APPEND ${C_VERSION_FILE} "#define TW686X_VERSION_MAJOR ${MAJOR_VERSION}\n")
file(APPEND ${C_VERSION_FILE} "#define TW686X_VERSION_MINOR ${MINOR_VERSION}\n")
file(APPEND ${C_VERSION_FILE} "#define TW686X_VERSION_PATCH ${PATCH_VERSION}\n")
file(APPEND ${C_VERSION_FILE} "#define TW686X_VERSION_SUFFIX \"${SUFFIX}\"\n")
file(APPEND ${C_VERSION_FILE} "#define TW686X_VERSION \"${VERSION}\"\n")
file(APPEND ${C_VERSION_FILE} "#define TW686X_GIT_HASH \"${GIT_HASH}\"\n")
file(APPEND ${C_VERSION_FILE} "#define TW686X_DATE \"${BUILD_DATE}\"\n")
file(APPEND ${C_VERSION_FILE} "\n")
file(APPEND ${C_VERSION_FILE} "#endif  // DRIVERS_TW686X_VERSION_H_\n")

 