[workspace]
members = [
    "examples/rust/cot",
    "examples/rust/joystick_rs",
    "examples/rust/zenoh/common",
    "examples/rust/zenoh/zenoh_example_subscriber",
    "examples/rust/zenoh/zenoh_example_simple",
]
