# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnss.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngnss.proto\x12\x04gnss\"\xdf\x01\n\x0bGNSSMessage\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x12\n\nposition_x\x18\x03 \x01(\x02\x12\x12\n\nposition_y\x18\x04 \x01(\x02\x12\x12\n\nposition_z\x18\x05 \x01(\x02\x12\x12\n\nrotation_x\x18\x06 \x01(\x02\x12\x12\n\nrotation_y\x18\x07 \x01(\x02\x12\x12\n\nrotation_z\x18\x08 \x01(\x02\x12\x10\n\x08pressure\x18\t \x01(\x02\x12\x0e\n\x06gforce\x18\n \x01(\x02\x12\x11\n\ttimestamp\x18\x0b \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gnss_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GNSSMESSAGE._serialized_start=21
  _GNSSMESSAGE._serialized_end=244
# @@protoc_insertion_point(module_scope)
