# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mr_motor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emr_motor.proto\x12\x04md80\"\xf8\x01\n\x07MrMotor\x12\x1c\n\x04mode\x18\x01 \x01(\x0e\x32\x0e.md80.Md80Mode\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x17\n\x0fposition_target\x18\x03 \x01(\x02\x12\x17\n\x0fvelocity_target\x18\x04 \x01(\x02\x12\x15\n\rtorque_target\x18\x05 \x01(\x02\x12\x12\n\nmax_torque\x18\x06 \x01(\x02\x12\x0f\n\x02kp\x18\x07 \x01(\x02H\x00\x88\x01\x01\x12\x0f\n\x02kd\x18\x08 \x01(\x02H\x01\x88\x01\x01\x12\x18\n\x10profile_velocity\x18\t \x01(\x02\x12\x1c\n\x14profile_acceleration\x18\n \x01(\x02\x42\x05\n\x03_kpB\x05\n\x03_kd*\x83\x01\n\x08Md80Mode\x12\x08\n\x04IDLE\x10\x00\x12\x10\n\x0cPOSITION_PID\x10\x01\x12\x10\n\x0cVELOCITY_PID\x10\x02\x12\x0e\n\nRAW_TORQUE\x10\x03\x12\r\n\tIMPEDANCE\x10\x04\x12\x14\n\x10POSITION_PROFILE\x10\x07\x12\x14\n\x10VELOCITY_PROFILE\x10\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mr_motor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MD80MODE._serialized_start=276
  _MD80MODE._serialized_end=407
  _MRMOTOR._serialized_start=25
  _MRMOTOR._serialized_end=273
# @@protoc_insertion_point(module_scope)
