name: "Ubuntu 24.04 x64"

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:24.04

    steps:
      - uses: actions/checkout@v3
      - name: Apt Update
        run: apt-get update

      - name: Apt Install
        run: |
          apt-get update
          ./setup.sh

      - name: CMake and Build
        run: |
          mkdir build 
          cd build
          cmake  ..
          make
